"""empty message

Revision ID: 53fdc27fc390
Revises: 
Create Date: 2018-04-23 19:24:39.180402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53fdc27fc390'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_issues', 'issue_proj',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('project_managers', 'manager_code',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.NVARCHAR(length=20),
               nullable=False)
    op.add_column('projects', sa.Column('proj_client', sa.NVARCHAR(length=20), nullable=True))
    op.alter_column('projects', 'proj_approval',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('projects', 'proj_description',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.NVARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('projects', 'proj_manager',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.NVARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('projects', 'proj_name',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.NVARCHAR(length=40),
               existing_nullable=False)
    op.create_foreign_key(None, 'projects', 'clients', ['proj_client'], ['client_id'])
    op.create_foreign_key(None, 'projects', 'project_managers', ['proj_manager'], ['manager_code'])
    op.create_foreign_key(None, 'projects', 'currency', ['proj_currency'], ['curr_id'])
    op.create_foreign_key(None, 'projects', 'project_types', ['proj_type'], ['type_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'proj_name',
               existing_type=sa.NVARCHAR(length=40),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('projects', 'proj_manager',
               existing_type=sa.NVARCHAR(length=20),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('projects', 'proj_description',
               existing_type=sa.NVARCHAR(length=1000),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('projects', 'proj_approval',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.drop_column('projects', 'proj_client')
    op.alter_column('project_managers', 'manager_code',
               existing_type=sa.NVARCHAR(length=20),
               type_=mysql.VARCHAR(length=15))
    op.alter_column('project_issues', 'issue_proj',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
