"""empty message

Revision ID: ede03d07e762
Revises: a35e2b4c4ecd
Create Date: 2018-04-25 16:55:42.655563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ede03d07e762'
down_revision = 'a35e2b4c4ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects_approvers')
    op.alter_column('project_disbursements', 'disbt_status',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('projects', 'proj_approval',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('users', sa.Column('disbursements_approval_rights', sa.Boolean(), nullable=False))
    op.alter_column('users', 'user_approver_rights',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_approver_rights',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.drop_column('users', 'disbursements_approval_rights')
    op.alter_column('projects', 'proj_approval',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('project_disbursements', 'disbt_status',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.create_table('projects_approvers',
    sa.Column('approver_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('approver_code', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('approver_code'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
